### ISSUE TITLE
Wrong IDs on the google spreadsheet

### ISSUE THREAD

**Issue by mpsido** [coderbunker/inventory-server#13]
some ids are repeated
other ids have a wrong format
some are empty.

**Comment by Spazcool** [comment]
My suggestion in issue #22 would alleviate this but, require a new assignment of stickers without a proper UUID.

**Comment by Spazcool** [comment]
Not a great fix but, it helps to spot them: I added some conditional formatting to the spreadsheet. The duplicate UUIDs backgrounds fill to yellow.

**Comment by lenzai** [comment]
would be nice to have a data validation with REGEX for UUID

**Comment by Spazcool** [comment]
@lenzai I've tested it against what combinations I could think of here's the data validation I came up with ```=REGEXMATCH(P86,"[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}")```

**Comment by lenzai** [comment]
perfect
