### ISSUE TITLE
don't load spreadsheet for wrong IDS

### ISSUE THREAD

**Issue by mpsido** [coderbunker/inventory-server#14]
We need equipment IDS to have a fixed pattern so we can recognize in advance invalid IDS and don't request the google spreadsheet for these ill shaped IDS

**Comment by lenzai** [comment]
This is not a bug. Just an opinion.

**Comment by mattermoran** [comment]
I would get a list of all IDs and store it locally and then before making request to the spreadsheet I would just check if ID match any that's already stored

**Comment by mattermoran** [comment]
And in the googleSpreadsheet.js file can add a method to check if there any new IDs, if there is some then add to the local json file.

**Comment by lenzai** [comment]
what's the goal for this issue? performance on optimization ? in which specific circumstances?

**Comment by lenzai** [comment]
@mpsido   after yesterday's discussion, is there still an issue?

**Comment by mpsido** [comment]
you can close the issue for now, we will see later  if we need that filtering, it is not costly in server side.
actually neither we do on spreadsheet side given the number of items we have we can handle redundant ids manually
this is part of perfectionement job that can be updated over time
