### ISSUE TITLE
broken links when items have no UUID

### ISSUE THREAD

**Issue by lenzai** [coderbunker/inventory-server#16]
e.g. http://localhost:1234/fridge

**Comment by Spazcool** [comment]
@lenzai is this not the same problem as issue #17 ? If the UUID is rubbish, the link will not work. This problem is not specific to the "similar item" links.

**Comment by lenzai** [comment]
Let's extend this issue to any broken links since the root cause is the same: lack of UUID

**Comment by Spazcool** [comment]
What should the page load if there is no info in the URL?

**Comment by lenzai** [comment]
1. what should be the target url if there are no item id?
2. what should the page of that target url should display?

**Comment by Spazcool** [comment]
1. Perhaps a search by item type page? Something to the effect: 'Oops, that item's QR label hasn't been entered into the database yet. Try searching by fixture type? || Here's a list of all items of a similar type.'

**Comment by Spazcool** [comment]
Notes to self: remove link, graphical shorthand...grayed out...
