### ISSUE TITLE
page not found returns status 200 instead of 404

### ISSUE THREAD

**Issue by lenzai** [coderbunker/inventory-server#2]
http://url.coderbunker.com/anything_not_found should set http status at 404

**Comment by Spazcool** [comment]
For this issue, should the page only render the 404 status ( 'Page not found')? Or should it still render our 'not found' template but with the page code 404?

**Comment by lenzai** [comment]
The only requirement is to comply with status 404 . Content is free choice. You can check http protocole documentation for more.
