### ISSUE TITLE
date default timezone is UTC on heroku

### ISSUE THREAD

**Issue by lenzai** [coderbunker/inventory-server#37]
On development station, the dates display with GMT+8 timezone.
On heroku server, it is set to GMT+8.

I tried to run `heroku config:add TZ="China/Shanghai"` and restart but it remains UTC.

**Comment by Spazcool** [comment]
Haven't set up Heroku yet on my machine, according to [wiki](https://en.wikipedia.org/wiki/List_of_tz_database_time_zones), you might need to write `heroku config:add TZ="Asia/Shanghai"`

**Comment by Spazcool** [comment]
Yep, fixed and running.
