### ISSUE TITLE
error 503

### ISSUE THREAD

**Issue by lenzai** [coderbunker/inventory-server#38]
http://url.coderbunker.com/favicon.ico returns error 503

**Comment by Spazcool** [comment]
I'm not getting this when run locally but I am getting a page with an empty response error

![faviconscreenshot](https://user-images.githubusercontent.com/17243640/33246949-4876596c-d355-11e7-943f-16e3fded37ac.png)

**Comment by lenzai** [comment]
maybe test on your own heroku instance

**Comment by Spazcool** [comment]
Have we run out of a free trial or something?
![herokudynos](https://user-images.githubusercontent.com/17243640/33356401-3eab7298-d4f7-11e7-94ef-8c024dbf02e3.png)
