### ISSUE TITLE
remove redirection to cryptic-woodland-88390

### ISSUE THREAD

**Issue by mpsido** [coderbunker/inventory-server#44]
The redirection to cryptic-woodland-88390 is there for historical reasons, but has nothing to do there in app.js source code.

As stated in the Readme.md file the heroku server we are deploying on is : 
enigmatic-brushlands-32514

We need to re-check what is the IP Adress the domain url.coderbunker.com points to.
But whatever is the registration in the domain name app.js is not the right place to redirect

Instead of a redirection we should create a home page.

**Comment by Spazcool** [comment]
Why not just redirect to the search page without any search parameters entered? It gets the user to a useful place and doesn't require building a whole new page.

**Comment by lenzai** [comment]
Let's just make a home page with a friendly invitation to start scanning

> "Go to Coderbunker and scan a QR code to get started. QR code are everywhere on every objects, they will help you go through the challenge of booking a thing , using a thing, fixing a thing or making things."
