### ISSUE TITLE
migrating hosting from heroku to Digital Ocean.

### ISSUE THREAD

**Issue by lenzai** [coderbunker/inventory-server#54]

**Comment by mpsido** [comment]
Still Fetching around solutions. Here are some possible implementations:
* using got hooks to provoke a deployment when we merge with in a deployment branch
* using Jenkins to configure continuous deployment. Jenkins has a git integration.
These two solutions still require a separately installed server applicatiom like apache

**Comment by mpsido** [comment]
Grunt js.
CircleCI add-on on within
Travis CI heroku itself may may be  based on that, it is also on github marketplace

**Comment by mpsido** [comment]
Still Fetching around solutions. Here are some possible implementations:
* using git hooks to provoke a deployment when we merge with in a deployment branch
* using Jenkins to configure continuous deployment. Jenkins has a git integration.
These two solutions still require a separately installed server applicatiom like apache

**Comment by lenzai** [comment]
Other Coderbunker commercial projects use Codeship

**Comment by mpsido** [comment]
https://digitalocean.com/community/tutorials/how-to-use-git-hooks-to-automate-development-and-deployment-tasks

**Comment by mpsido** [comment]
https://www.digitalocean.com/community/tutorials/how-to-use-git-hooks-to-automate-development-and-deployment-tasks

**Comment by lenzai** [comment]
Current deployment seems like running 2 instances of node. Therefore, each on each one of them is managing a separate list for "recentScans"

**Comment by mpsido** [comment]
thank you for this feedback.
I see what is going on. if we want to keep the advantage of multi instances we have to find a solution to store local variables in a local memory.
i can make a temporary fix where i only allow one instance. all it takes is modifying process.yml file., but not today

**Comment by lenzai** [comment]
Really not a priority to support multi ancestry. The feature was a hack to
leverage on single instance deployment. We can just wipe out the feature
and replace with true analytic solution rather than further expanding code
complexity. Anyway, this is not a concern in deployment automation.

**Comment by lenzai** [comment]
Besides , we are currently hosting on a single core instance
