### ISSUE TITLE
http to https redirect is not working within WeChat browser.

### ISSUE THREAD

**Issue by lenzai** [coderbunker/inventory-server#75]
Can we rollback from https until this is resolved?

**Comment by xuyuji9000** [comment]
Used Ruud's android phone's wechat tested the qrcode scan, it worked.

QR Code:

![image](https://user-images.githubusercontent.com/4877346/36627514-f70a95dc-197e-11e8-945c-fda67c0e716c.png)

Scan Result:

![image](https://user-images.githubusercontent.com/4877346/36627505-d9e464ba-197e-11e8-95ec-72d759ff97e4.png)

**Comment by xuyuji9000** [comment]
It should be the legacy SSL certificate cache corrupte the url rendering.

![image](https://user-images.githubusercontent.com/4877346/36628677-510d70d2-1988-11e8-8253-73773c51d79d.png)

This one says, change your account on wechat, will clear the cookie, maybe useful for SSL certificate

**Comment by mpsido** [comment]
![screenshot_20180224-174300](https://user-images.githubusercontent.com/18638060/36629010-efa3ade2-1915-11e8-838d-f4bf301be03c.png)

this message shows uo on my phone browser but not on my computer. I guess this is a matter of trusted certification authority. maybe Lets Encrypt is not trusted by my phone's browser
