### ISSUE TITLE
pre-commit fails

### ISSUE THREAD

**Issue by mpsido** [coderbunker/inventory-server#8]
pre-commit fails with following error messages.

`inventory-server/app.js
  18:29  error  Arrow function used ambiguously with a conditional expression                              no-confusing-arrow
  26:37  error  Unexpected parentheses around single function argument having a body with no curly braces  arrow-parens
  26:48  error  Multiple spaces found before 'item'                                                        no-multi-spaces
  27:44  error  Unexpected parentheses around single function argument having a body with no curly braces  arrow-parens
  27:55  error  Multiple spaces found before 'matches'                                                     no-multi-spaces

inventory-server/googleSpreadsheet.js
  23:41  error  Unexpected parentheses around single function argument having a body with no curly braces                                                                                  arrow-parens
  30:5   error  iterators/generators require regenerator-runtime, which is too heavyweight for this guide to allow them. Separately, loops should be avoided in favor of array iterations  no-restricted-syntax
  31:7   error  Assignment to function parameter 'rows'                                                                                                                                    no-param-reassign
  31:26  error  Unexpected parentheses around single function argument having a body with no curly braces                                                                                  arrow-parens

✖ 9 problems (9 errors, 0 warnings)
  7 errors, 0 warnings potentially fixable with the `--fix` option.

pre-commit: 
pre-commit: We've failed to pass the specified git pre-commit hooks as the `lint`
pre-commit: hook returned an exit code (1). If you're feeling adventurous you can
pre-commit: skip the git pre-commit hooks by adding the following flags to your commit:
pre-commit: 
pre-commit:   git commit -n (or --no-verify)
pre-commit: 
pre-commit: This is ill-advised since the commit is broken.
pre-commit: 
`

**Comment by mattermoran** [comment]
Well it tells you exactly why it fails. Just fix all errors to pass eslint and you'll be good to go

**Comment by lenzai** [comment]
closed with  commit 294c4233e5362b200adeba562c472e82c37d6c93
